# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fI4caxn4gtCiLrpz0l36lBgn23MNiYWp
"""

import streamlit as st
from PIL import Image
import numpy as np
from moviepy.editor import ImageClip, concatenate_videoclips
import os
import tempfile

# --- 1. FUNÇÃO DE GERAÇÃO DE VÍDEO (O MOTOR DA IA) ---
def create_cartoon_animation(image_path, duration_sec, fps):
    """
    Cria uma animação de zoom e pan (movimento lateral) a partir de uma imagem.
    Usa o MoviePy para gerar o vídeo final.
    """
    try:
        # Carrega a imagem
        img = Image.open(image_path).convert("RGB")
        width, height = img.size

        # Converte a imagem PIL para um array numpy (formato que o MoviePy usa)
        np_img = np.array(img)

        # 1. Movimento de Zoom In (Clip 1)
        # O MoviePy permite animar a propriedade 'pos' (posição) ou 'resize' (redimensionar)
        zoom_duration = duration_sec / 2

        # Cria um clipe de imagem
        clip_zoom = ImageClip(np_img, duration=zoom_duration)

        # Aplica uma transformação de zoom simples (do tamanho 1.0 ao 1.2)
        clip_zoom = clip_zoom.fx(
            lambda get_frame, t: clip_zoom.get_frame(t) * (1 + 0.2 * t / zoom_duration)
        )

        # 2. Movimento de Pan Horizontal (Clip 2)
        # Corta uma área e move a área de corte horizontalmente (simulando um pan)
        pan_duration = duration_sec - zoom_duration

        # Define a função de pan (move o quadro de visualização)
        def pan_frame(t):
            # Calcula o percentual de tempo decorrido
            t_percent = t / pan_duration

            # Define o tamanho do corte (zoom in 1.1x)
            crop_size_w = int(width / 1.1)
            crop_size_h = int(height / 1.1)

            # Posição inicial (x_start) e final (x_end) do canto superior esquerdo
            x_start = 0
            # x_end é o máximo que podemos mover para o lado sem sair da imagem
            x_end = width - crop_size_w

            # Posição x atual (Pan da esquerda para a direita)
            x_current = int(x_start + t_percent * (x_end - x_start))

            # y é constante (mantemos no topo, por exemplo)
            y_current = 0

            # Corta a imagem (crop)
            cropped_img = img.crop((x_current, y_current, x_current + crop_size_w, y_current + crop_size_h))

            # Retorna o frame como um array numpy
            return np.array(cropped_img)

        clip_pan = ImageClip(np_img, duration=pan_duration).set_make_frame(pan_frame)

        # Junta os dois clipes
        final_clip = concatenate_videoclips([clip_zoom, clip_pan], method="compose")
        final_clip = final_clip.set_fps(fps)

        # Salva o arquivo de vídeo temporário
        with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as temp_file:
            output_path = temp_file.name

        final_clip.write_videofile(
            output_path,
            codec='libx264',
            audio_codec='aac',
            temp_audiofile='temp-audio.m4a',
            remove_temp=True,
            verbose=False,
            logger=None
        )

        return output_path

    except Exception as e:
        st.error(f"Erro ao gerar o vídeo: {e}")
        return None


# --- 2. INTERFACE STREAMLIT ---
st.set_page_config(page_title="Gerador de Vídeo Cartunesco", layout="wide")
st.title("🎬 Gerador de Vídeo Cartunesco (MoviePy)")

st.sidebar.header("Configurações")

# Carregamento da imagem (Permite upload ou usa a imagem do anexo como referência)
uploaded_file = st.file_uploader(
    "1. Carregue sua imagem de desenho cartunesco:",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:
    # Salva o arquivo temporariamente para o MoviePy poder ler pelo caminho
    with tempfile.NamedTemporaryFile(delete=False) as tmp_file:
        tmp_file.write(uploaded_file.read())
        image_path = tmp_file.name

    # Exibir a imagem carregada
    st.subheader("Imagem Carregada")
    st.image(image_path, use_column_width=True)

    st.subheader("Ajustes de Animação")

    # Parâmetros
    duration = st.sidebar.slider("Duração do Vídeo (segundos)",
                                 min_value=3, max_value=10, value=5)
    fps = st.sidebar.slider("Quadros por Segundo (FPS)",
                            min_value=10, max_value=30, value=24)

    if st.button("2. Gerar Animação"):
        with st.spinner(f"Criando vídeo de {duration}s..."):

            video_output_path = create_cartoon_animation(image_path, duration, fps)

            if video_output_path:
                st.subheader("Vídeo Gerado!")

                # Leitura dos bytes do vídeo para exibição no Streamlit
                with open(video_output_path, "rb") as video_file:
                    video_bytes = video_file.read()

                st.video(video_bytes, format='video/mp4')

                # Opção de Download
                st.download_button(
                    label="Baixar Vídeo MP4",
                    data=video_bytes,
                    file_name="animacao_cartunesca.mp4",
                    mime="video/mp4"
                )

                # Limpa o arquivo temporário
                os.unlink(video_output_path)

            # Limpa a imagem temporária
            os.unlink(image_path)

else:
    st.info("Aguardando o upload da sua imagem cartunesca para começar.")